[package]
name = "weval"
version = "0.1.0"
authors = ["Chris Fallin <chris@cfallin.org>"]
license = "Apache-2.0 WITH LLVM-Exception"
edition = "2021"

[dependencies]
waffle = { path = "../waffle", version = "*" }
anyhow = "*"
structopt = "*"
walrus = "*"
wasm-encoder = "*"
wasmparser = "*"
log = "*"
env_logger = "*"
