[package]
name = "weval"
version = "0.1.0"
authors = ["Chris Fallin <chris@cfallin.org>"]
license = "Apache-2.0 WITH LLVM-Exception"
edition = "2021"

[dependencies]
waffle = "0.0.3"
anyhow = "*"
structopt = "*"
wasm-encoder = "*"
wasmparser = "*"
log = "*"
env_logger = "*"
